name: Cypress Tests with Allure for Multiple Browsers

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    name: Run tests in ${{ matrix.browser }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results

  merge-and-report:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Merge Allure results and generate report
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure artifacts for chrome
        uses: actions/download-artifact@v4
        with:
          name: allure-results-chrome
          path: downloaded-artifacts/chrome

      - name: Download Allure artifacts for firefox
        uses: actions/download-artifact@v4
        with:
          name: allure-results-firefox
          path: downloaded-artifacts/firefox

      - name: Download Allure artifacts for edge
        uses: actions/download-artifact@v4
        with:
          name: allure-results-edge
          path: downloaded-artifacts/edge

      - name: Merge Allure results
        run: |
          mkdir -p combined-results
          echo "Looking for downloaded artifacts..."
          find downloaded-artifacts -type d -exec cp -r {}/* combined-results/ \;
          echo "Contents of combined-results:"
          ls -R combined-results || echo "No results found"

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xvzf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate combined-results --clean -o allure-report
          ls -l allure-report || echo "Allure report not generated"

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
