name: Run Cypress Tests with Allure Reports

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    name: Run tests in ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress is installed
        run: npx cypress verify

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npx npx cypress run --browser ${{ matrix.browser }} --reporter mocha-allure-reporter


      - name: "Debug: Check allure-results"
        run: |
          echo "Current directory:"
          pwd
          echo "List files:"
          ls -la
          echo "Check allure-results:"
          ls -la allure-results || echo "Directory 'allure-results' not found"

      - name: Upload Allure results
        if: success() && hashFiles('allure-results/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results

  generate-report:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Generate merged Allure report

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: "Debug: Show downloaded artifacts"
        run: |
          echo "Downloaded artifacts:"
          ls -R downloaded-artifacts || echo "Nothing found"

      - name: Combine results
        run: |
          mkdir -p combined-results
          if [ -d "downloaded-artifacts" ]; then
            find downloaded-artifacts -type d -exec cp -r {}/* combined-results/ \;
          else
            echo "No artifacts found to merge."
            exit 1
          fi
          echo "Contents of combined-results:"
          ls -R combined-results || echo "No results found"

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline
          allure generate combined-results --clean -o allure-report
          ls -R allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
