name: Cypress Tests with Allure Report (Multi-Browser)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    runs-on: ubuntu-latest
    name: Run tests in ${{ matrix.browser }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Clean previous Allure results
        run: rm -rf cypress-logs/allure-results || true

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}

      - name: Debug: List Allure results
        run: |
          echo "Checking allure-results folder:"
          ls -la cypress-logs/allure-results || echo "Directory not found"

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: cypress-logs/allure-results
          if-no-files-found: warn

  generate-report:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Generate merged Allure Report
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Merge Allure results
        run: |
          mkdir -p combined-results
          echo "Looking for downloaded artifacts..."
          find downloaded-artifacts -type d -exec cp -r {}/* combined-results/ \;
          echo "Contents of combined-results:"
          ls -R combined-results || echo "No results found"

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: combined-results
          allure_report: allure-report
          keep_reports: true

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
