name: Cypress Tests with Allure

on:
  push:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }}

      - name: Upload Allure results for ${{ matrix.browser }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: cypress/allure-results
          if-no-files-found: ignore

  merge-and-publish-report:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          path: all-results

      - name: Combine Allure results
        run: |
          mkdir -p combined-results
          find all-results -type d -name 'allure-results*' -exec cp -r {}/* combined-results/ \;

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: combined-results
          allure_report: allure-report
          keep_reports: true

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
