name: cypress-run

on:

    push:
     branches:
        - main

jobs:
    run-cypress-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                browser: [chrome, firefox, edge]
        name: Run Cypress tests on ${{ matrix.browser }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3  

            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18
        
            - name: Install dependencies
              run: npm ci
        
            - name: Run Cypress tests on ${{ matrix.browser }}
              run: |
                echo "BROWSER=${{ matrix.browser }}" > cypress.env.json
                npx cypress run --browser ${{ matrix.browser }} --e2e
        
            - name: Upload Allure results
              uses: actions/upload-artifact@v4
              with:
                name: allure-results-${{ matrix.browser }}
                path: ./allure-results
