name: Cypress Chrome + Allure

on:
  schedule:
    - cron: '0 12 * * 1-5' # 6:00 AM GMT-6 → 12:00 UTC
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Chrome
        run: npx cypress run --browser chrome

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  build-allure-report:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          ls -R allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/*

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages

  send-email:
    runs-on: ubuntu-latest
    needs: build-allure-report

    steps:
      - name: Send Allure Report URL via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Allure Report: Cypress Chrome'
          to: tmqa2408@gmail.com
          from: GitHub CI <${{ secrets.EMAIL_USERNAME }}>
          body: |
            ✅ Тесты завершены. Отчёт Allure доступен по ссылке:
            👉 https://tmqa2408.github.io/cypress_Cucumber_BDD
