name: Cypress Tests with Allure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]

    name: Run tests in ${{ matrix.browser }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        env:
          CYPRESS_BROWSER: ${{ matrix.browser }}
        run: |
          npx cypress run --browser $CYPRESS_BROWSER

      - name: Check allure-results content
        run: |
          echo "Checking allure results for ${{ matrix.browser }}"
          ls -R cypress-logs/allure-results || echo "No Allure results found!"

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: cypress-logs/allure-results
          if-no-files-found: warn

  merge-and-generate-report:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Merge Allure Results and Generate Report

    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Check downloaded artifacts
        run: |
          echo "Downloaded contents:"
          ls -R downloaded-artifacts || echo "No downloaded artifacts found!"

      - name: Merge Allure Results
        run: |
          mkdir -p combined-results
          if [ -d "downloaded-artifacts" ]; then
            find downloaded-artifacts -type d -exec cp -r {}/* combined-results/ \;
          else
            echo "No artifacts found to merge."
            exit 1
          fi

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: |
          allure generate combined-results --clean -o allure-report
          ls -R allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
